# Generated by Django 4.0.3 on 2022-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True)),
                ('eamil', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
