# Generated by Django 4.0.3 on 2022-04-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='eamil',
            new_name='email',
        ),
    ]
